# Spring and other bootstrap configs

server:
  port: 28080

integration:
  self-care:
    rest:
      host: "http://172.28.27.2:9676/live/CPEManager/IntegrationInterfaces/SelfCare/REST"
      username: "SELFCARENEW_SOAP"
      password: "Yfpfhtyrj#4"

logging:
  pattern:
    console: '%d{dd-MM-yyyy HH:mm:ss.SSS} [%-22thread] %-5level %-35logger{0}: %msg%n'
  level:
    org:
      springframework:
        web: DEBUG
        ws:
          server:
            MessageTracing:
              sent: DEBUG
              received: TRACE
          client:
            MessageTracing:
              received: TRACE
              sent: TRACE