# Spring and other bootstrap configs

server:
  port: 28080

fdms:
  host: "http://172.28.27.2:9676/live/CPEManager/IntegrationInterfaces/SelfCare/SOAP"
  username: "SELFCARENEW_SOAP"
  password: "Yfpfhtyrj#4"